from __future__ import annotations

from enum import Enum
from typing import Optional

from syncfusion.utils import CustomBaseModel

from .core import SlideItem, SlideItemType


class PlaceholderType(str, Enum):
    BITMAP = "Bitmap"
    BODY = "Body"
    CENTERTITLE = "CenterTitle"
    CHART = "Chart"
    DATE = "Date"
    FOOTER = "Footer"
    HEADER = "Header"
    MEDIACLIP = "MediaClip"
    OBJECT = "Object"
    ORGANIZATIONCHART = "OrganizationChart"
    PICTURE = "Picture"
    SLIDEIMAGE = "SlideImage"
    SLIDENUMBER = "SlideNumber"
    SUBTITLE = "Subtitle"
    TABLE = "Table"
    TITLE = "Title"
    VERTICALBODY = "VerticalBody"
    VERTICALOBJECT = "VerticalObject"
    VERTICALTITLE = "VerticalTitle"


class PlaceholderFormat(CustomBaseModel):
    Name: Optional[str] = None
    Type: PlaceholderType


class AutoShapeType(str, Enum):
    ARC = "Arc"
    BENT_ARROW = "BentArrow"
    BENT_CONNECTOR2 = "BentConnector2"
    BENT_CONNECTOR4 = "BentConnector4"
    BENT_CONNECTOR5 = "BentConnector5"
    BENT_UP_ARROW = "BentUpArrow"
    BEVEL = "Bevel"
    BLOCK_ARC = "BlockArc"
    CAN = "Can"
    CHEVRON = "Chevron"
    CHORD = "Chord"
    CIRCULAR_ARROW = "CircularArrow"
    CLOUD = "Cloud"
    CLOUD_CALLOUT = "CloudCallout"
    CORNER = "Corner"
    CROSS = "Cross"
    CUBE = "Cube"
    CURVED_CONNECTOR = "CurvedConnector"
    CURVED_CONNECTOR2 = "CurvedConnector2"
    CURVED_CONNECTOR4 = "CurvedConnector4"
    CURVED_CONNECTOR5 = "CurvedConnector5"
    CURVED_DOWN_ARROW = "CurvedDownArrow"
    CURVED_DOWN_RIBBON = "CurvedDownRibbon"
    CURVED_LEFT_ARROW = "CurvedLeftArrow"
    CURVED_RIGHT_ARROW = "CurvedRightArrow"
    CURVED_UP_ARROW = "CurvedUpArrow"
    CURVED_UP_RIBBON = "CurvedUpRibbon"
    DECAGON = "Decagon"
    DIAGONAL_STRIPE = "DiagonalStripe"
    DIAMOND = "Diamond"
    DODECAGON = "Dodecagon"
    DONUT = "Donut"
    DOUBLE_BRACE = "DoubleBrace"
    DOUBLE_BRACKET = "DoubleBracket"
    DOUBLE_WAVE = "DoubleWave"
    DOWN_ARROW = "DownArrow"
    DOWN_ARROW_CALLOUT = "DownArrowCallout"
    DOWN_RIBBON = "DownRibbon"
    ELBOW_CONNECTOR = "ElbowConnector"
    EXPLOSION1 = "Explosion1"
    EXPLOSION2 = "Explosion2"
    FLOW_CHART_ALTERNATE_PROCESS = "FlowChartAlternateProcess"
    FLOW_CHART_CARD = "FlowChartCard"
    FLOW_CHART_COLLATE = "FlowChartCollate"
    FLOW_CHART_CONNECTOR = "FlowChartConnector"
    FLOW_CHART_DATA = "FlowChartData"
    FLOW_CHART_DECISION = "FlowChartDecision"
    FLOW_CHART_DELAY = "FlowChartDelay"
    FLOW_CHART_DIRECT_ACCESS_STORAGE = "FlowChartDirectAccessStorage"
    FLOW_CHART_DISPLAY = "FlowChartDisplay"
    FLOW_CHART_DOCUMENT = "FlowChartDocument"
    FLOW_CHART_EXTRACT = "FlowChartExtract"
    FLOW_CHART_MAGNETIC_DISK = "FlowChartMagneticDisk"
    FLOW_CHART_MANUAL_INPUT = "FlowChartManualInput"
    FLOW_CHART_MANUAL_OPERATION = "FlowChartManualOperation"
    FLOW_CHART_MERGE = "FlowChartMerge"
    FLOW_CHART_MULTI_DOCUMENT = "FlowChartMultiDocument"
    FLOW_CHART_OFF_PAGE_CONNECTOR = "FlowChartOffPageConnector"
    FLOW_CHART_OR = "FlowChartOr"
    FLOW_CHART_PREDEFINED_PROCESS = "FlowChartPredefinedProcess"
    FLOW_CHART_PREPARATION = "FlowChartPreparation"
    FLOW_CHART_PROCESS = "FlowChartProcess"
    FLOW_CHART_PUNCHED_TAPE = "FlowChartPunchedTape"
    FLOW_CHART_SEQUENTIAL_ACCESS_STORAGE = "FlowChartSequentialAccessStorage"
    FLOW_CHART_SORT = "FlowChartSort"
    FLOW_CHART_STORED_DATA = "FlowChartStoredData"
    FLOW_CHART_SUMMING_JUNCTION = "FlowChartSummingJunction"
    FLOW_CHART_TERMINATOR = "FlowChartTerminator"
    FOLDED_CORNER = "FoldedCorner"
    FRAME = "Frame"
    FUNNEL = "Funnel"
    GEAR6 = "Gear6"
    GEAR9 = "Gear9"
    HALF_FRAME = "HalfFrame"
    HEART = "Heart"
    HEPTAGON = "Heptagon"
    HEXAGON = "Hexagon"
    HORIZONTAL_SCROLL = "HorizontalScroll"
    ISOSCELES_TRIANGLE = "IsoscelesTriangle"
    LEFT_ARROW = "LeftArrow"
    LEFT_ARROW_CALLOUT = "LeftArrowCallout"
    LEFT_BRACE = "LeftBrace"
    LEFT_BRACKET = "LeftBracket"
    LEFT_CIRCULAR_ARROW = "LeftCircularArrow"
    LEFT_RIGHT_ARROW = "LeftRightArrow"
    LEFT_RIGHT_ARROW_CALLOUT = "LeftRightArrowCallout"
    LEFT_RIGHT_RIBBON = "LeftRightRibbon"
    LEFT_RIGHT_UP_ARROW = "LeftRightUpArrow"
    LEFT_UP_ARROW = "LeftUpArrow"
    LIGHTNING_BOLT = "LightningBolt"
    LINE = "Line"
    LINE_CALLOUT1 = "LineCallout1"
    LINE_CALLOUT1_ACCENT_BAR = "LineCallout1AccentBar"
    LINE_CALLOUT1_BORDER_AND_ACCENT_BAR = "LineCallout1BorderAndAccentBar"
    LINE_CALLOUT1_NO_BORDER = "LineCallout1NoBorder"
    LINE_CALLOUT2 = "LineCallout2"
    LINE_CALLOUT2_ACCENT_BAR = "LineCallout2AccentBar"
    LINE_CALLOUT2_BORDER_AND_ACCENT_BAR = "LineCallout2BorderAndAccentBar"
    LINE_CALLOUT2_NO_BORDER = "LineCallout2NoBorder"
    LINE_CALLOUT3 = "LineCallout3"
    LINE_CALLOUT3_ACCENT_BAR = "LineCallout3AccentBar"
    LINE_CALLOUT3_BORDER_AND_ACCENT_BAR = "LineCallout3BorderAndAccentBar"
    LINE_CALLOUT3_NO_BORDER = "LineCallout3NoBorder"
    MATH_DIVISION = "MathDivision"
    MATH_EQUAL = "MathEqual"
    MATH_MINUS = "MathMinus"
    MATH_MULTIPLY = "MathMultiply"
    MATH_NOT_EQUAL = "MathNotEqual"
    MATH_PLUS = "MathPlus"
    MOON = "Moon"
    NO_SYMBOL = "NoSymbol"
    NOTCHED_RIGHT_ARROW = "NotchedRightArrow"
    OCTAGON = "Octagon"
    OVAL = "Oval"
    OVAL_CALLOUT = "OvalCallout"
    PARALLELOGRAM = "Parallelogram"
    PENTAGON = "Pentagon"
    PIE = "Pie"
    PIE_WEDGE = "PieWedge"
    PLAQUE = "Plaque"
    QUAD_ARROW = "QuadArrow"
    QUAD_ARROW_CALLOUT = "QuadArrowCallout"
    RECTANGLE = "Rectangle"
    RECTANGULAR_CALLOUT = "RectangularCallout"
    REGULAR_PENTAGON = "RegularPentagon"
    RIGHT_ARROW = "RightArrow"
    RIGHT_ARROW_CALLOUT = "RightArrowCallout"
    RIGHT_BRACE = "RightBrace"
    RIGHT_BRACKET = "RightBracket"
    RIGHT_TRIANGLE = "RightTriangle"
    ROUND_DIAGONAL_CORNER_RECTANGLE = "RoundDiagonalCornerRectangle"
    ROUNDED_RECTANGLE = "RoundedRectangle"
    ROUNDED_RECTANGULAR_CALLOUT = "RoundedRectangularCallout"
    ROUND_SAME_SIDE_CORNER_RECTANGLE = "RoundSameSideCornerRectangle"
    ROUND_SINGLE_CORNER_RECTANGLE = "RoundSingleCornerRectangle"
    SMILEY_FACE = "SmileyFace"
    SNIP_AND_ROUND_SINGLE_CORNER_RECTANGLE = "SnipAndRoundSingleCornerRectangle"
    SNIP_DIAGONAL_CORNER_RECTANGLE = "SnipDiagonalCornerRectangle"
    SNIP_SAME_SIDE_CORNER_RECTANGLE = "SnipSameSideCornerRectangle"
    SNIP_SINGLE_CORNER_RECTANGLE = "SnipSingleCornerRectangle"
    STAR10_POINT = "Star10Point"
    STAR12_POINT = "Star12Point"
    STAR16_POINT = "Star16Point"
    STAR24_POINT = "Star24Point"
    STAR32_POINT = "Star32Point"
    STAR4_POINT = "Star4Point"
    STAR5_POINT = "Star5Point"
    STAR6_POINT = "Star6Point"
    STAR7_POINT = "Star7Point"
    STAR8_POINT = "Star8Point"
    STRAIGHT_CONNECTOR = "StraightConnector"
    STRIPED_RIGHT_ARROW = "StripedRightArrow"
    SUN = "Sun"
    SWOOSH_ARROW = "SwooshArrow"
    TEARDROP = "Teardrop"
    TRAPEZOID = "Trapezoid"
    UNKNOWN = "Unknown"
    UP_ARROW = "UpArrow"
    UP_ARROW_CALLOUT = "UpArrowCallout"
    UP_DOWN_ARROW = "UpDownArrow"
    UP_DOWN_ARROW_CALLOUT = "UpDownArrowCallout"
    UP_RIBBON = "UpRibbon"
    U_TURN_ARROW = "UTurnArrow"
    VERTICAL_SCROLL = "VerticalScroll"
    WAVE = "Wave"


class Shape(SlideItem):  # Inherits from SlideItem
    SlideItemType: SlideItemType = SlideItemType.AUTOSHAPE  # Add default value
    AutoShapeType: "AutoShapeType"  # Use string for forward reference
    Fill: Optional["Fill"] = None  # Use string for forward reference
    TextBody: Optional["TextBody"] = None  # Use string for forward reference
    Rotation: Optional[int] = 0


class SolidFill(CustomBaseModel):
    Color: str


class Fill(CustomBaseModel):
    FillType: str = "Solid"  # Add default value
    SolidFill: Optional[SolidFill] = None


# Rebuild the model
Shape.model_rebuild()
